<?php


namespace Tests\Unit\Rules;


use App\Models\Category;
use App\Models\Genre;
use App\Rules\GenresHasCategoriesRules;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Mockery\MockInterface;
use Tests\TestCase;

class GenresHasCategoriesRuleTest extends TestCase
{
    use DatabaseMigrations;

    private $categories;
    private $genres;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->categories = factory(Category::class, 4)->create();
        $this->genres = factory(Genre::class, 2)->create();

        $this->genres[0]->categories()->sync([
            $this->categories[0]->id,
            $this->categories[1]->id,
        ]);

        $this->genres[1]->categories()->sync([
            $this->categories[2]->id
        ]);
    }

    public function testPassesIsValid()
    {
        $rule = new GenresHasCategoriesRules(
            [
                $this->categories[2]->id
            ]
        );

        $isValid = $rule->passes('', [
            $this->genres[1]->id
        ]);

        $this->assertTrue($isValid);


        $rule = new GenresHasCategoriesRules(
            [
                $this->categories[0]->id,
                $this->categories[2]->id
            ]
        );

        $isValid = $rule->passes('', [
            $this->genres[0]->id,
            $this->genres[1]->id
        ]);

        $this->assertTrue($isValid);


        $rule = new GenresHasCategoriesRules(
            [
                $this->categories[0]->id,
                $this->categories[1]->id,
                $this->categories[2]->id
            ]
        );

        $isValid = $rule->passes('', [
            $this->genres[0]->id,
            $this->genres[1]->id
        ]);

        $this->assertTrue($isValid);

    }

    public function testPassesIsNotValid()
    {
        $rule = new GenresHasCategoriesRules(
            [
                $this->categories[0]->id
            ]
        );

        $isValid = $rule->passes('', [
            $this->genres[0]->id,
            $this->genres[1]->id
        ]);

        $this->assertFalse($isValid);
    }

}