version: '3'

services:

  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:5432 --timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/wwww
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/wwww
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3006:3006"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



