<?php

namespace Tests\Feature\Http\Controllers\Api\Video;

use App\Models\Video;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

abstract class BaseVideoControllerTestCase extends TestCase
{
    use DatabaseMigrations;

    protected $video;
    protected $sendData;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->video = factory(Video::class)->create();
        $this->sendData = [
            'title' => 'Test Video Test',
            'description' => 'Testes phpunit',
            'year_launched' => 2019,
            'opened' => false,
            'rating' => Video::RATING_LIST[0],
            'duration' => rand(30, 60)
        ];
    }

    protected function routeStore()
    {
        return route('videos.store');
    }

    protected function routeUpdate()
    {
        return route('videos.update', ['video' => $this->video->id]);
    }

    protected function model()
    {
        return Video::class;
    }

}
